using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Linq;
using BAL;
using DAL;

namespace GUI
{
    public partial class frmBanHang : Form
    {
        string Conn;
        private GetTaiKhoan taiKhoan;
        BanHangBAL BanHangBAL;
        List<DonHangBAL> lDanhSachDonhang = new List<DonHangBAL>();
        string idKhachhang;
        string hotenKhachhang;
        frmDonHang frm;


        public GetTaiKhoan TaiKhoan { get => taiKhoan; set => taiKhoan = value; }

        public frmBanHang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource

        }
        public frmBanHang(GetTaiKhoan taikhoan,string conn)
        {
            Conn = conn;
            this.TaiKhoan = taikhoan;
            BanHangBAL = new BanHangBAL(conn);
            frm = new frmDonHang(Conn, "BanHang");
            InitializeComponent();
        }

        private void frmBanHang_Load(object sender, EventArgs e)
        {
            foreach (Form _mdiForm in this.MdiChildren)
                if(_mdiForm.Name == frm.Name)
                {
                    lDanhSachDonhang = frm.DanhSachDonHang1;
                    uint tongtien = 0;
                    for (int i = 0; i < lDanhSachDonhang.Count; i++)
                    {
                        tongtien += UInt32.Parse(ChuyenVeChuoiThuong(lDanhSachDonhang[i].ThanhTien));

                    }
                    txtTongTien.ResetText();
                    txtTongTien.Text = ChuyenVeChuoiTien(tongtien.ToString());
                    gcThanhToan.Enabled = true;
                }         
        }
        void LoadForm(object sender ,EventArgs e)
        {
            gcThanhToan.Enabled = false;
            btnOK.Enabled = false;
            btnCancel.Enabled = false;
            btnDone2.Enabled = false;
            txtKhachHang.ResetText();
            txtTongTien.ResetText();
            txtTienNhan.ResetText(); 
            txtTienThua.ResetText();
            txtMaHD.ResetText();
            txtNhanVien.ResetText();
            txtKhachHang.ResetText();
            dNgayLap.ResetText();
            btnNext_Click(sender, e);
            btnThietLapDonHang.Enabled = false;
            btnThietLapDonHang.Text = "Thiết Lập Đơn Hàng";
        }

        private void btnLoadThongTinKhachHang_Click(object sender, EventArgs e)
        {
            ISingleResult<TimKhachHangResult> x = BanHangBAL.LayThongTinKhachHang(txtNhapID.Text);
            gridBanHang.DataSource = x;
            if(gridView1.RowCount > 0)
            {
                btnDone.Enabled = true;
              
            }


            
        }

        private void txtNhapID_TextChanged(object sender, EventArgs e)
        {

        }
       
        private void btnAddNew_Click(object sender, EventArgs e)
        {
            frmThemKhachHang frm = new frmThemKhachHang(Conn);
            frm.ShowDialog();
            idKhachhang = frm.Id;
            hotenKhachhang = frm.Hoten;
            if (idKhachhang != null)
            {
                txtNhapID.ResetText();
                txtNhapID.Text = idKhachhang;
                btnLoadThongTinKhachHang_Click(sender, e);
                txtNhapID.ResetText();
            }
            
        }

        private void btnNext_Click(object sender, EventArgs e)
        {
            btnThietLapDonHang.Enabled = true;

            txtMaHD.ResetText();
            txtNhanVien.ResetText();
            txtKhachHang.ResetText();

            dNgayLap.ResetText();
            gcLapHoaDon.Enabled = true;
            int n = BanHangBAL.SoLuongHoaDon()+1;
            if (n < 99)
                txtMaHD.Text = "HDX0" + n.ToString();
            else
                txtMaHD.Text = "HDX" + n.ToString();
            idKhachhang = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, colNguoiID).ToString();
            hotenKhachhang = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, colhoTen).ToString();
            txtKhachHang.Text = hotenKhachhang;
            dNgayLap.Text = DateTime.Now.ToString("MM/dd/yyyy");
            txtNhanVien.Text = TaiKhoan.hoTen;

          


        }

        private void btnGioHang_Click(object sender, EventArgs e)
        {
            
        }

      
        public string ChuyenVeChuoiTien(string x)
        {
            int n = x.Length;
            if (n % 3 == 0 && n > 3) 
            {
                for (int i = n / 3 - 1; i >0 ; i--)
                {
                    x = x.Insert(i * 3 , " ");
                }
            }
            else
            {
                if (n % 3 == 1 && n > 3) 
                {
                    for (int i = n / 3; i > 0; i--)
                    {
                        x = x.Insert(i * 3 -(n/3) , " ");
                    }
                }
                else
                {
                    if (n > 3)
                    {
                        for (int i = n / 3; i > 0; i--)
                        {
                            x = x.Insert(i * 3 - 1, " ");
                        }
                    }
                }
            }
            return x;
        }
        public string ChuyenVeChuoiThuong(string x)
        {
            for (int i = 0; i < x.Length; i++)
            {
                if (x[i] == ' ')
                    x = x.Remove(i, 1);
            }
            return x;
        }

       

        private void txtSoLuong_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!Char.IsDigit(e.KeyChar) && !Char.IsControl(e.KeyChar))
                e.Handled = true;
        }

        
        
        private void txtTienNhan_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (!Char.IsDigit(e.KeyChar) && !Char.IsControl(e.KeyChar))
                e.Handled = true;

        }

        private void txtTienNhan_TextChanged(object sender, EventArgs e)
        {
            btnOK.Enabled = true;

        }

        private void btnOK_Click(object sender, EventArgs e)
        {
            string x = ChuyenVeChuoiTien(txtTienNhan.Text);
            txtTienNhan.ResetText();
            txtTienNhan.Text = x;
            if (Int32.Parse(ChuyenVeChuoiThuong(txtTienNhan.Text)) < Int32.Parse(ChuyenVeChuoiThuong(txtTongTien.Text)))
                MessageBox.Show("Chưa Nhận Đủ Tiền");
            else
            {
                txtTienThua.Text = ChuyenVeChuoiTien((Int32.Parse(ChuyenVeChuoiThuong(txtTienNhan.Text)) - Int32.Parse(ChuyenVeChuoiThuong(txtTongTien.Text))).ToString());
            }
        }

        private void txtTienThua_TextChanged(object sender, EventArgs e)
        {
            btnDone2.Enabled = true;
            btnCancel.Enabled = true;
        }

        private void btnDone2_Click(object sender, EventArgs e)
        {
            DialogResult tl = MessageBox.Show("Xác Nhận Giao Dịch ?", "Xác Nhận", MessageBoxButtons.OKCancel, MessageBoxIcon.Question);
            if(tl==DialogResult.OK)
            {
                string maHD = txtMaHD.Text;

                //idKhachhang

                string idNV = taiKhoan.ID;
                DateTime ngayLap = DateTime.Parse(dNgayLap.Text);
                try
                {
                    for (int i = 0; i < lDanhSachDonhang.Count; i++)
                    {
                        int soLuong = lDanhSachDonhang[i].SoLuong;
                        string maHang = "";
                        int n = lDanhSachDonhang[i].TenHang.IndexOf('_', 0);
                        maHang = lDanhSachDonhang[i].TenHang.Substring(n + 1);                   
                        BanHangBAL.ThucHienGiaoDich(maHD,maHang,  idKhachhang, soLuong, idNV, ngayLap);
                    }
                    MessageBox.Show("Lập Hóa Đơn Giao Dịch Thành Công", "Thông Báo");
                    LoadForm(sender, e);
                }
                catch(Exception ex)
                { 
                   MessageBox.Show(ex.ToString(), "Thông Báo");
                }
            }

        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void txtTienNhan_Click(object sender, EventArgs e)
        {
            txtTienNhan.ResetText();
        }

        private void btnThietLapDonHang_Click(object sender, EventArgs e)
        {

           
            if (btnThietLapDonHang.Text == "Thiết Lập Đơn Hàng")
            {
                frm.ShowDialog();
                /*lDanhSachDonhang = frm.DanhSachDonHang1;
                uint tongtien = 0;
                for (int i = 0; i < lDanhSachDonhang.Count; i++)
                {ng(lDanhSachDonhang[i].ThanhTien));

                }
                txtTongTien.Text = ChuyenVeChuoiTien(tongtien.
                    tongtien += UInt32.Parse(ChuyenVeChuoiThuoToString());
                gcThanhToan.Enabled = true;*/
                btnThietLapDonHang.Text = "Xem Lại Đơn Hàng";
                btnDone1.Enabled = true;

            }
            else
            {

                frm.Show();

            }




        }

        private void frmBanHang_EnabledChanged(object sender, EventArgs e)
        {
            if (frm.ActiveMdiChild != null)
            {
                lDanhSachDonhang = frm.DanhSachDonHang1;
                uint tongtien = 0;
                for (int i = 0; i < lDanhSachDonhang.Count; i++)
                {
                    tongtien += UInt32.Parse(ChuyenVeChuoiThuong(lDanhSachDonhang[i].ThanhTien));

                }
                txtTongTien.ResetText();
                txtTongTien.Text = ChuyenVeChuoiTien(tongtien.ToString());
                gcThanhToan.Enabled = true;
            }
        }

        private void btnDone1_Click(object sender, EventArgs e)
        {
            lDanhSachDonhang = frm.DanhSachDonHang1;
            uint tongtien = 0;
            for (int i = 0; i < lDanhSachDonhang.Count; i++)
            {
                tongtien += UInt32.Parse(ChuyenVeChuoiThuong(lDanhSachDonhang[i].ThanhTien));

            }
            txtTongTien.ResetText();
            txtTongTien.Text = ChuyenVeChuoiTien(tongtien.ToString());
            gcThanhToan.Enabled = true;
            
        }
    }
}
