using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BAL;
using DAL;
namespace GUI
{
    public partial class frmHoaDonNhap : Form
    {
        HoaDonBAL HoaDonBAL;
        public frmHoaDonNhap(string conn)
        {
            HoaDonBAL = new HoaDonBAL(conn); 
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
          
        }

        private void frmHoaDonNhap_Load(object sender, EventArgs e)
        {

        }
        void LoadData()
        {
            gridHoaDonNhap.DataSource = HoaDonBAL.LayHoaDonNhap();
        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            LoadData();
        }
    }
}
