using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BAL;
using DAL;

namespace GUI
{
    public partial class frmPhanQuyen : Form
    {
        PhanQuyenBAL PhanQuyenBAL;
        private GetTaiKhoan taiKhoan;

        public GetTaiKhoan TaiKhoan { get => taiKhoan; set => taiKhoan = value; }

        public frmPhanQuyen(string conn)
        {
            PhanQuyenBAL = new PhanQuyenBAL(conn);
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard

            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            
        }

        private void btnLoad_Click(object sender, EventArgs e)
        {
            LoadData();
        }
        void LoadData()
        {
            gridPhanQuyen.DataSource = PhanQuyenBAL.LayUser();
        }

        private void btnSave_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            string x = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, colID).ToString();
            string y =  gridView1.GetRowCellValue(gridView1.FocusedRowHandle, colPassWord).ToString();
            System.Nullable<bool> a = (System.Nullable<bool>)gridView1.GetRowCellValue(gridView1.FocusedRowHandle, colQLBH);
            //TaiKhoan.QLBH = a;
            System.Nullable<bool> b = (System.Nullable<bool>)gridView1.GetRowCellValue(gridView1.FocusedRowHandle, colQLNK);
           // TaiKhoan.QLNK= b;
            System.Nullable<bool> c = (System.Nullable<bool>)gridView1.GetRowCellValue(gridView1.FocusedRowHandle, colQLNS);
            //TaiKhoan.QLNS= c;
            System.Nullable<bool> d = (System.Nullable<bool>)gridView1.GetRowCellValue(gridView1.FocusedRowHandle, colThongKe);
           // TaiKhoan.ThongKe = d;
            System.Nullable<bool> f = (System.Nullable<bool>)gridView1.GetRowCellValue(gridView1.FocusedRowHandle, colPQuyen);
           // TaiKhoan.PQuyen = f;
            try
            {
                PhanQuyenBAL.UpdateTaiKhoan(x, y, (bool)a, (bool)b, (bool)c, (bool)d, (bool)f);
                MessageBox.Show("Cập Nhập Thành Công");
            }
            catch { MessageBox.Show("Không Cập Nhập Thành Công"); }
            
        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void gridPhanQuyen_Click(object sender, EventArgs e)
        {

        }

        private void frmPhanQuyen_Load(object sender, EventArgs e)
        {

        }
    }
}
